Some methods of numpy 

# Attributes

In [1]:
# first we import numpy
import numpy as np

In [2]:
# now we are avaliable to use its methods

# 1_Dimension array

In [8]:

l = np.array([0,1,2,3,4,5])
l

array([0, 1, 2, 3, 4, 5])

In [10]:
l.ndim     # 1

1

In [11]:
l.size     #2

6

In [12]:
l.dtype    #3

dtype('int32')

In [13]:
l.itemsize   #4

4

In [14]:
l.dtype.itemsize   #5 tell about size of byte

4

In [17]:
l.data     #6

# 2_Dimension array

In [18]:
# to convert an array in the form of 2d we use reshape function

In [28]:
a = np.arange(20).reshape(2,10)
a


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [30]:
a.shape  #1

(2, 10)

In [32]:
a.ndim  #2

2

In [34]:
a.size  #3

20

In [36]:
a.dtype  #4

dtype('int32')

In [38]:
a.data  #5

In [43]:
a = np.array([(1,2,3,4),(5,6,7,8)])

In [44]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Methods

#zeros method 
np.zeros((3,3))  #1

In [53]:
np.zeros(3)   #

array([0., 0., 0.])

In [55]:
# ones method
np.ones(9)    #2

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
np.empty((1,9))  #3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
l = np.eye(10)
l             #4

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [74]:
np.diag(l)   #5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [75]:
np.random.randint(0,10,2)

array([1, 2])

In [76]:
np.random.randn(10)

array([-0.49589619, -1.36954428,  0.06269201, -1.51287557, -0.61034763,
       -1.10490109,  0.61438171, -0.20961638, -0.31959983,  0.25384967])